# NumPy

NumPy est une bibliothèque pour langage de programmation Python, destinée à manipuler des matrices ou tableaux multidimensionnels ainsi que des fonctions mathématiques opérant sur ces tableaux.

Plus précisément, cette bibliothèque logicielle libre et open source fournit de multiples fonctions permettant notamment de créer directement un tableau depuis un fichier ou au contraire de sauvegarder un tableau dans un fichier, et manipuler des vecteurs, matrices et polynômes.

NumPy est la base de SciPy, regroupement de bibliothèques Python autour du calcul scientifique.

- `np.array()` : permet de convertir une `list` en `numpy.ndarray`.

In [43]:
import numpy as np

L = np.array([1, 2, 3, 4])
print(L)
print(type(L))

[1 2 3 4]
<class 'numpy.ndarray'>


On peut constater que dans la sortie, que contrairement à une liste en Python, les éléments ne sont pas séparés par des `,` (virgules).

- `np.arange()` : genère un array à partir d'un interval, on peut préciser un pas optionnel ; on s'arrête à l'avant dernier élément.

In [44]:
L = np.arange(1, 10)
print(L)
M = np.arange(1, 10, 0.5)
print(M)

[1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


- `np.linspace()` : Cette fonction permet de génerer un array contenant un interval de nombres, coupés x fois.

In [45]:
L = np.linspace(0, 1, num=2)
print(L)
M = np.linspace(0, 1, num=3)
print(M)
N = np.linspace(0, 1, num=4)
print(N)
O = np.linspace(0, 1, num=5)
print(O)

[0. 1.]
[0.  0.5 1. ]
[0.         0.33333333 0.66666667 1.        ]
[0.   0.25 0.5  0.75 1.  ]


- `np.zeros()/np.ones()` : permet de créer un vecteurs remplis de x zéros ou de x uns.

In [46]:
L = np.zeros(5)
print(L)
M = np.ones(5) * 7
print(M)

[0. 0. 0. 0. 0.]
[7. 7. 7. 7. 7.]


- `np.random.random()` : permet de créer un vecteurs remplis de x nombres compris entre 0 et 1 tirés au hasard.

In [70]:
L = np.random.random(3)
print(L)

[0.54047586 0.44771476 0.81105775]


- `np.sin(), np.cos(), np.tan(), ...` : ces fonctions permettent d'appliquer des fonctions mathématiques à un array.

In [71]:
L = np.arange(-10, -1)
print(L)
print(np.abs(L))

[-10  -9  -8  -7  -6  -5  -4  -3  -2]
[10  9  8  7  6  5  4  3  2]


On a :

- `np.sqrt()` : racine carré
- `np.exp()` : exponentielle
- `np.log()` : logarithme
- `np.abs()` : valeur absolue
- `np.sin()` : sinus
- `np.cos()` : cosinus
- `np.tan()` : tangente
- `np.sinh()` : sinus hyperbolique
- `np.cosh()` : cosinus hyperbolique
- `np.tanh()` : tangente hyperbolique
- `np.sign()` : signe

## Opérations sur les Tableau (Array)

On peut facilement effectuer des opérations sur tout les éléments d'un `np.ndarray` :

In [72]:
X = np.array([1, 2, 3, 4])
print(X*2)
print(X+1)
print(X**2) # puissance n

[2 4 6 8]
[2 3 4 5]
[ 1  4  9 16]


On peut également faire la **somme** de tout les éléments d'un tableau :

In [73]:
print(np.sum(X))

10


On peut aussi faire la somme ou le produit de deux tableau :

In [50]:
Y = np.array([2, 3, 4, 5])

print(X+Y)
print(X*Y)

[3 5 7 9]
[ 2  6 12 20]


Ou bien afficher la valeur **minimale/maximale** présente dans la liste :

In [51]:
print(np.max(X))

4


In [52]:
print(np.min(X))

1


## Accès sur les Arrays

L'accès aux arrays NumPy se fait comme les listes en Python.

In [53]:
L = np.linspace(0, 1, 4)
print(L)

[0.         0.33333333 0.66666667 1.        ]


In [54]:
print(L[0])

0.0


In [55]:
print(L[1])

0.3333333333333333


In [56]:
print(L[-1])

1.0


In [57]:
print(L[1:])

[0.33333333 0.66666667 1.        ]


In [58]:
print(L[:-1])

[0.         0.33333333 0.66666667]


In [59]:
print(L[1:-1])

[0.33333333 0.66666667]


In [60]:
for x in L : print(x)

0.0
0.3333333333333333
0.6666666666666666
1.0


In [61]:
for k in range(len(L)) : print(k, L[k])

0 0.0
1 0.3333333333333333
2 0.6666666666666666
3 1.0
